/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package Views;

import Controllers.AsistenciaControl;
import Controllers.UserControl;
import java.sql.*;
import Models.Conexion;
import Models.UserModel;
import Services.Clock;
import java.beans.PropertyVetoException;
import java.util.HashMap;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JDesktopPane;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import org.bytedeco.opencv.opencv_videoio.VideoCapture;

/**
 *
 * @author sebas_j2dhfxw
 */
public class MenuTrabajador extends javax.swing.JInternalFrame {

    int idTrabajador;

    /**
     * Creates new form MenuTrabajador
     */
    public MenuTrabajador(int id) {
        initComponents();
        idTrabajador = id;

        runClock();
        saludarUsuario(id);
        cargarJornada("Matutino", jtblMatutina);
        cargarJornada("Vespertino", jtblVespertina);
        cargarDatosUsuario();
        //cargarJornada("Vespertino");

        // Intentar maximizar el JInternalFrame
        /*try {
            setMaximum(true);
        } catch (PropertyVetoException ex) {
            ex.printStackTrace();
        }
         */
        this.closable = true;
        this.resizable = true;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */

    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jtblTablaUsuario = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jtblVespertina = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jtblMatutina = new javax.swing.JTable();

        jtblTablaUsuario.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(jtblTablaUsuario);

        jLabel1.setFont(new java.awt.Font("Sitka Banner", 1, 48)); // NOI18N
        jLabel1.setText("jLabel1");

        jLabel2.setFont(new java.awt.Font("Segoe UI Symbol", 1, 18)); // NOI18N
        jLabel2.setText("Bienvenido : ");

        jButton1.setText("Registrar ");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Ver reportes");

        jLabel3.setText("Jornada de registros");

        jtblVespertina.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane2.setViewportView(jtblVespertina);

        jLabel4.setText("Jornada Matutina");

        jLabel5.setText("Jornada Vespertina");

        jtblMatutina.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane3.setViewportView(jtblMatutina);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 525, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 525, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(101, 101, 101)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel2)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(216, 216, 216)
                            .addComponent(jLabel1))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(200, 200, 200)
                            .addComponent(jLabel3))
                        .addGroup(layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 538, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(19, 19, 19)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel4)
                                .addComponent(jLabel5)))))
                .addContainerGap(9, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel2)
                .addGap(29, 29, 29)
                .addComponent(jLabel1)
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addGap(17, 17, 17)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46)
                .addComponent(jLabel5)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(55, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
    }//GEN-LAST:event_jButton1ActionPerformed
    public void runClock() {
        Conexion con = new Conexion();
        Clock relog = new Clock(con.conectar(), jLabel1);
        Thread hiloReloj = new Thread(relog);
        hiloReloj.start();
    }

    private String obtenerCedula(int id) {
        try {
            Conexion cx = new Conexion();
            Connection cn = cx.conectar();
            String sql = "Select ced_usu from usuarios where id_usu = ? ";
            PreparedStatement st = cn.prepareStatement(sql);
            st.setInt(1, id);
            ResultSet rs = st.executeQuery();
            String nombre = "";
            while (rs.next()) {
                nombre = rs.getString("ced_usu");
            }
            return nombre;
        } catch (SQLException ex) {
            Logger.getLogger(MenuTrabajador.class.getName()).log(Level.SEVERE, null, ex);
        }
        return null;
    }

    public void saludarUsuario(int id) {
        try {
            Conexion cx = new Conexion();
            Connection cn = cx.conectar();
            String sql = "Select nom_usu ,ape_usu from usuarios where id_usu = ? ";
            PreparedStatement st = cn.prepareStatement(sql);
            st.setInt(1, id);
            ResultSet rs = st.executeQuery();
            while (rs.next()) {
                String nombre = rs.getString("nom_usu");
                String apellido = rs.getString("ape_usu");
                jLabel2.setText("Bienvenido: " + nombre + " " + apellido);
            }

        } catch (SQLException ex) {
            Logger.getLogger(MenuTrabajador.class.getName()).log(Level.SEVERE, null, ex);
        }

    }

    private void cargarDatosUsuario() {
        Conexion cc = new Conexion();

        try (Connection cn = cc.conectar()) {
            String[] nombres = {"Cedula", "Entrada Jornada", "Salida Jornada"};
            DefaultTableModel modelo = new DefaultTableModel(nombres, 0); // Inicia sin filas
            jtblTablaUsuario.setModel(modelo);
            String sql = "SELECT ced_usu, sue_usu from usuarios where id_usu=? ";

            try (PreparedStatement st = cn.prepareStatement(sql)) {
                // Impresiones de depuración
                st.setInt(1, idTrabajador);

                try (ResultSet resultSet = st.executeQuery()) {
                    while (resultSet.next()) {
                        String cedula = resultSet.getString("ced_usu");

                        modelo.addRow(new Object[]{cedula, "8:00", "17:00"});
                    }
                }
            } catch (SQLException ex) {
                Logger.getLogger(MenuTrabajador.class.getName()).log(Level.SEVERE, null, ex);
            }

        } catch (SQLException ex) {
            Logger.getLogger(MenuTrabajador.class.getName()).log(Level.SEVERE, null, ex);
        } // La conexión se cerrará automáticamente al salir del bloque try-with-resources
    }

    private void cargarJornada(String Horario, JTable tabla) {
        Conexion cc = new Conexion();
        Connection cn = cc.conectar();

        String[] titulos = {"Cedula", "Nombres", "Hora Registro Ingreso", "Hora Registro Salida"};
        DefaultTableModel modelo2 = new DefaultTableModel(titulos, 0);
        tabla.setModel(modelo2);

        String sql = "SELECT u.ced_usu, u.nom_usu, u.ape_usu, i.fec_hor_ing, s.fec_hor_sal\n"
                + "FROM app_visual.usuarios u\n"
                + "LEFT JOIN app_visual.ingresos i ON u.ced_usu = i.id_usu\n"
                + "LEFT JOIN app_visual.salidas s ON u.ced_usu = s.id_usu_sal\n"
                + "WHERE u.id_usu = ?\n"
                + "AND DATE(i.fec_hor_ing) = DATE(s.fec_hor_sal)\n"
                + "AND i.HOR_ASI = ?\n"
                + "AND s.HOR_ASI = ?\n"
                + "AND DATE(i.fec_hor_ing) = CURRENT_DATE";

        try (PreparedStatement st = cn.prepareStatement(sql)) {
            // Impresiones de depuración
            System.out.println("idTrabajador: " + obtenerCedula(idTrabajador));
            System.out.println("Horario: " + Horario);

            st.setInt(1, idTrabajador);
            st.setString(2, Horario);
            st.setString(3, Horario);

            try (ResultSet resultSet = st.executeQuery()) {
                while (resultSet.next()) {
                    int cedula = resultSet.getInt("ced_usu");
                    String nombre = resultSet.getString("nom_usu");
                    String apellido = resultSet.getString("ape_usu");
                    String ingreso = resultSet.getString("fec_hor_ing");
                    String salida = resultSet.getString("fec_hor_sal");

                    modelo2.addRow(new Object[]{cedula, nombre + " " + apellido, ingreso, salida});
                }
            }
        } catch (SQLException ex) {
            Logger.getLogger(MenuTrabajador.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

   public void registros (){
       
   }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jtblMatutina;
    private javax.swing.JTable jtblTablaUsuario;
    private javax.swing.JTable jtblVespertina;
    // End of variables declaration//GEN-END:variables
}
