/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package Views;
import java.sql.ResultSet;
import Controllers.UserControl;
import Models.Conexion;
import java.awt.Dimension;
import java.sql.Connection;
import java.util.HashMap;
import java.util.Map;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JDesktopPane;
import javax.swing.JInternalFrame;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.DefaultTableModel;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author davay
 */
public class ReportesAdmin extends javax.swing.JInternalFrame {
    String idUser;
    String nomUser;
    String mesTexto = "Enero";
    String mesNum = "01";
    String fechaF;
    String anio;
    
    JDesktopPane Escritorio;
    public ReportesAdmin(JDesktopPane Escritorio) {
        this.Escritorio = Escritorio;
        initComponents();
        this.cargarTabla();
        this.cargarCombo();
        jtbUsers.getSelectionModel().addListSelectionListener(new ListSelectionListener() {
            @Override
            public void valueChanged(ListSelectionEvent e) {
                if (jtbUsers.getSelectedRow() != -1) {
                   idUser = jtbUsers.getValueAt(jtbUsers.getSelectedRow(), 0).toString();
                   nomUser = jtbUsers.getValueAt(jtbUsers.getSelectedRow(), 1).toString() + " " +jtbUsers.getValueAt(jtbUsers.getSelectedRow(), 2).toString();
                }
            }
        });

    }
        private void centrarVentana() {
        Dimension desktopSize = Escritorio.getSize();
        Dimension jInternalFrameSize = this.getSize();
        int width = (desktopSize.width - jInternalFrameSize.width) / 2;
        int height = (desktopSize.height - jInternalFrameSize.height) / 2;
        this.setLocation(width, height);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtbUsers = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jbtRetrasos = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jftAnio = new javax.swing.JFormattedTextField();
        jLabel3 = new javax.swing.JLabel();
        jcbMeses = new javax.swing.JComboBox<>();

        setClosable(true);
        setMaximizable(true);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jtbUsers.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jtbUsers.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Title 1", "Title 2", "Title 3"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jtbUsers);
        if (jtbUsers.getColumnModel().getColumnCount() > 0) {
            jtbUsers.getColumnModel().getColumn(0).setResizable(false);
        }

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 40, -1, 90));

        jLabel1.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Ingrese el mes:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, 100, -1));

        jbtRetrasos.setText("Atrasos");
        jbtRetrasos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtRetrasosActionPerformed(evt);
            }
        });
        jPanel1.add(jbtRetrasos, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 290, 140, 70));

        jButton1.setText("Sueldos");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 290, 150, 70));

        jLabel2.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Seleccione el empleado:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 200, -1));

        jftAnio.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(new java.text.SimpleDateFormat("y"))));
        jPanel1.add(jftAnio, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 150, 130, -1));

        jLabel3.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Ingrese el año:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, 100, -1));

        jcbMeses.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbMesesActionPerformed(evt);
            }
        });
        jPanel1.add(jcbMeses, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 200, 150, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 377, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtRetrasosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtRetrasosActionPerformed
    this.reporteAtrasos();
    }//GEN-LAST:event_jbtRetrasosActionPerformed
    
    //reporte de multas
    public void reporteAtrasos(){
    if (this.idUser != null) {
    try {
        Conexion cc = new Conexion();
        Connection cn = cc.conectar();
        this.anio = this.jftAnio.getText();
        this.fechaF = this.anio+"-"+ this.mesNum;
        Map<String, Object> parametros = new HashMap<>();
        parametros.put("nom_user", this.nomUser);
        parametros.put("mes", this.mesTexto);
        parametros.put("anio", this.anio);
        parametros.put("fechaF", this.fechaF);
        parametros.put("id_user", this.idUser);
        
        
        

        JasperReport reporte = JasperCompileManager.compileReport("src/Views/reportAdminRetrasos.jrxml");
        JasperPrint print = JasperFillManager.fillReport(reporte, parametros, cn);

        // Mostrar el reporte en un InternalFrame
        JInternalFrame internalFrame = new JInternalFrame("Informe de multas", true, true, true, true);
        internalFrame.setSize(600, 400);

        // Agregar el visor del informe al InternalFrame
        JasperViewer viewer = new JasperViewer(print, false);
        internalFrame.getContentPane().add(viewer.getContentPane());

        // Agregar el InternalFrame al JDesktopPane
        Escritorio.add(internalFrame);
        internalFrame.setVisible(true);
    } catch (JRException ex) {
        System.out.println(ex);
    }
}
    }
    
    private void jcbMesesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbMesesActionPerformed
    this.mesTexto = String.valueOf(this.jcbMeses.getSelectedItem());
    this.mesNum = String.valueOf(this.jcbMeses.getSelectedIndex()+1);
        if (this.mesNum.length()==1) {
            this.mesNum = "0"+this.mesNum;
        }
    }//GEN-LAST:event_jcbMesesActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        this.reporteSueldos();
    }//GEN-LAST:event_jButton1ActionPerformed
    
    
    //reporte de sueldos
    public void reporteSueldos(){
    if (this.idUser != null) {
    try {
        
        Conexion cc = new Conexion();
        Connection cn = cc.conectar();
        this.anio = this.jftAnio.getText();
        this.fechaF = this.anio+"-"+ this.mesNum;
        Map<String, Object> parametros = new HashMap<>();
        parametros.put("nomC", this.nomUser);
        parametros.put("id_user", this.idUser);
        parametros.put("mesT", this.mesTexto);
        parametros.put("anio", this.anio);
        parametros.put("fechaC", this.fechaF);
        System.out.println(this.nomUser + " " + this.idUser+ this.fechaF);
        JasperReport reporte = JasperCompileManager.compileReport("src/Views/reportAdminSueldos.jrxml");
        JasperPrint print = JasperFillManager.fillReport(reporte, parametros, cn);

        // Mostrar el reporte en un InternalFrame
        JInternalFrame internalFrame = new JInternalFrame("Informe de multas", true, true, true, true);
        internalFrame.setSize(600, 400);

        // Agregar el visor del informe al InternalFrame
        JasperViewer viewer = new JasperViewer(print, false);
        internalFrame.getContentPane().add(viewer.getContentPane());

        // Agregar el InternalFrame al JDesktopPane

        Escritorio.add(internalFrame);
        internalFrame.setVisible(true);
    } catch (JRException ex) {
        System.out.println(ex);
    }
    }
    }
    
    public void cargarTabla(){
        
        try {
            UserControl controller = new UserControl();
            String[] columnas = {"Cédula", "Nombre", "Apellido"};
            
            DefaultTableModel model = new DefaultTableModel(columnas, 0) {
                @Override
                public boolean isCellEditable(int row, int column) {
                    // No permitir edición de celdas
                    return false;
                }
            };
            ResultSet rs = controller.getUsers();
            while (rs.next()) {
                
                String cedula = rs.getString("CED_USU");
                
                String nombre = rs.getString("NOM_USU");
                String apellido = rs.getString("APE_USU");
                model.addRow(new Object[]{cedula, nombre, apellido});
            }
            
            this.jtbUsers.setModel(model);
            this.jtbUsers.getTableHeader().setReorderingAllowed(false);
        } catch (Exception ex) {
            System.out.println(ex);
        }
    }
    public void cargarCombo(){
    String[] meses = {
            "Enero", "Febrero", "Marzo", "Abril",
            "Mayo", "Junio", "Julio", "Agosto",
            "Septiembre", "Octubre", "Noviembre", "Diciembre"
    };
    DefaultComboBoxModel modeloCombo = new DefaultComboBoxModel(meses);
    this.jcbMeses.setModel(modeloCombo);

    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbtRetrasos;
    private javax.swing.JComboBox<String> jcbMeses;
    private javax.swing.JFormattedTextField jftAnio;
    private javax.swing.JTable jtbUsers;
    // End of variables declaration//GEN-END:variables
}
